In [1]:
# importing the necessary libraries
import cv2
import numpy as np





In [2]:
# Creating a VideoCapture object to read the video
cap = cv2.VideoCapture('video_cp.mp4')


In [3]:
ret, frame = cap.read()
print(frame)

[[[ 81  74  71]
  [ 81  74  71]
  [ 81  74  71]
  ...
  [197 195 191]
  [197 195 191]
  [197 195 191]]

 [[ 81  74  71]
  [ 81  74  71]
  [ 81  74  71]
  ...
  [197 195 191]
  [197 195 191]
  [197 195 191]]

 [[ 81  74  71]
  [ 81  74  71]
  [ 81  74  71]
  ...
  [197 195 191]
  [197 195 191]
  [197 195 191]]

 ...

 [[ 42  48  77]
  [ 44  50  79]
  [ 44  50  79]
  ...
  [ 33  33  45]
  [ 32  32  44]
  [ 33  33  45]]

 [[ 42  49  76]
  [ 43  50  77]
  [ 44  50  79]
  ...
  [ 33  33  45]
  [ 32  32  44]
  [ 32  32  44]]

 [[ 42  49  76]
  [ 43  50  77]
  [ 44  50  79]
  ...
  [ 33  33  45]
  [ 32  32  44]
  [ 32  32  44]]]


In [5]:
# Loop until the end of the video
while (cap.isOpened()):

	# Capture frame-by-frame
	ret, frame = cap.read()
	frame = cv2.resize(frame, (54, 54), fx = 0, fy = 0,
						interpolation = cv2.INTER_CUBIC)

	# Display the resulting frame
	cv2.imshow('Frame', frame)

	# conversion of BGR to grayscale is necessary to apply this operation
	gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

	# adaptive thresholding to use different threshold
	# values on different regions of the frame.
	Thresh = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_MEAN_C,
										cv2.THRESH_BINARY_INV, 11, 2)

	cv2.imshow('Thresh', Thresh)
	# define q as the exit button
	if cv2.waitKey(25) & 0xFF == ord('q'):
		break

# release the video capture object
cap.release()
# Closes all the windows currently opened.
cv2.destroyAllWindows()


error: OpenCV(4.5.3) /tmp/pip-req-build-afu9cjzs/opencv/modules/imgproc/src/resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'resize'


In [1]:
# Loop until the end of the video
while (cap.isOpened()):
    # Capture frame-by-frame
    ret, frame = cap.read()
    frame = cv2.resize(frame, (54, 54), fx = 0, fy = 0,
                         interpolation = cv2.INTER_CUBIC)
 
    # Display the resulting frame
    cv2.imshow('Frame', frame)
 
    # using cv2.Gaussianblur() method to blur the video
 
    # (5, 5) is the kernel size for blurring.
    gaussianblur = cv2.GaussianBlur(frame, (5, 5), 0)
    cv2.imshow('gblur', gaussianblur)
 
    # define q as the exit button
    if cv2.waitKey(25) & 0xFF == ord('q'):
        break
 
# release the video capture object
cap.release()
 
# Closes all the windows currently opened.
cv2.destroyAllWindows()

NameError: name 'cap' is not defined