In [1]:
import pandas as pd
import numpy as np
import re 
from sklearn.preprocessing import normalize

In [2]:
vocab = pd.read_csv('brown_vocab_100.txt' , header =None , sep='delimiter')
print(vocab.shape)

<ipython-input-2-05a61e7aa38b>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  vocab = pd.read_csv('brown_vocab_100.txt' , header =None , sep='delimiter')


(813, 1)


In [3]:
# vocab.head(2)

In [40]:
word_index_dict = {}
vocab = vocab[0]

# for ind, word in enumerate(vocab): 
#     word_index_dict[word] = ind

##############################################################

with open("brown_vocab_100.txt") as f:
    vocab = [line.rstrip('\n') for line in f]


for ind, word in enumerate(vocab): 
    word_index_dict[word] = ind
    
    
def save_dict_to_file(dic):
    f = open('word_to_index_100.txt','w')
    f.write(str(dic))
    f.close()

def load_dict_from_file():
    f = open('word_to_index_100.txt','r')
    data=f.read()
    f.close()
    return eval(data)

In [37]:
save_dict_to_file(word_index_dict1)

In [44]:
# load_dict_from_file()

In [9]:
print(word_index_dict['all'])
print(word_index_dict['resolution'])
print(len(word_index_dict))


0
812
813


In [14]:
# Question 2 : 
# brown = pd.read_csv('brown_100.txt' , header =None , sep='delimiter')
# brown.head(3)

In [1]:
# #dataframe
# a2 = np.zeros(813, dtype = "int")
# for sent in brown[0]:
#     text1 = re.sub('<s>|</s>', ' ', sent)
#     text2 = text1.lower().strip().split()
#     for word in text2:
#         if word in word_index_dict:
#             a2[word_index_dict[word]] = a2[word_index_dict[word]] +1
            
# a2

In [ ]:
#question 2) file

In [4]:
with open("brown_100.txt") as f:
    brown = [line.rstrip('\n') for line in f]
#     brown = f.readline()
# brown = brown[0]
# brown

In [5]:
len(brown)

100

In [13]:
brown[0]

"<s> The Fulton County Grand Jury said Friday an investigation of Atlanta's recent primary election produced `` no evidence '' that any irregularities took place . </s> "

In [49]:
#file 

def load_dict_from_file():
    f = open('word_to_index_100.txt','r')
    data=f.read()
    f.close()
    return eval(data)

word_index_dict = load_dict_from_file()
# word_index_dict

In [50]:

def count_word(word_input, word_index_dict_input):
    count_vector = np.zeros(813, dtype = "int")
    for sent in word_input:
        text1 = re.sub('<s>|</s>', ' ', sent)
        text2 = text1.lower().strip().split()
        for word in text2:
            if word in word_index_dict_input:
                count_vector[word_index_dict_input[word]] = count_vector[word_index_dict_input[word]] +1
                
    return count_vector

# a2 = np.zeros(813, dtype = "int")
# for sent in brown:
#     text1 = re.sub('<s>|</s>', ' ', sent)
#     text2 = text1.lower().strip().split()
#     for word in text2:
#         if word in word_index_dict:
#             a2[word_index_dict[word]] = a2[word_index_dict[word]] +1
            
# # a2

In [237]:
arr2 = count_word(brown, word_index_dict)
# arr2

In [94]:
arr2.shape, len(arr2)

(813,)

In [95]:
# len(arr2)

In [127]:
probs = (arr2 / np.sum(arr2))
# probs

In [97]:
probs[0] , probs[-1]

(0.0004409171075837742, 0.003968253968253968)

In [98]:
"""
Write your new probs vector to a file called unigram_probs.txt and verify that the first probability in it
(the probability of ‘all’) is 0.00040519 and that the last probability (probability of ‘resolution’) is 0.00364668.
(Note that our model trained on this small corpus has estimated that ‘resolution’ is about 10 times as frequent as 
‘all’! Models trained on very small corpora are very noisy.)
"""

'\nWrite your new probs vector to a file called unigram_probs.txt and verify that the first probability in it\n(the probability of ‘all’) is 0.00040519 and that the last probability (probability of ‘resolution’) is 0.00364668.\n(Note that our model trained on this small corpus has estimated that ‘resolution’ is about 10 times as frequent as \n‘all’! Models trained on very small corpora are very noisy.)\n'

In [99]:
import math as m
m.ceil(6.8)

7

In [100]:

# text = brown[0][0]


# text1 = re.sub('<s>|</s>', ' ', text)

# print(text1)

In [10]:
a = np.zeros(813 , dtype = "int")
# a

In [102]:
def get_value(dic, value):
    for k, v in dic.items():
        if k == value:
            return v

In [103]:
# get_value(d, "rob")

In [104]:
def GENERATE(word_index_dict, probs, model_type, max_words, start_word):
    returnSTR = ""
    index_word_dict = {v: k for k, v in word_index_dict.items()}
    num_words = 0

    #been passed a list of probabilities
    if model_type == "unigram":

        #using https://stackoverflow.com/questions/483666/python-reverse-invert-a-mapping
        while(True):
            wordIndex = np.random.choice(len(word_index_dict), 1, p=list(probs))
            word = index_word_dict[wordIndex[0]]
            returnSTR += word + " "
            num_words +=1
            if word == "</s>" or num_words == max_words:
                break

        return returnSTR

    #been passed a matrix of probabilities, where each row is the previous word. 
    if model_type == "bigram":
        returnSTR = start_word + " "
        prevWord = start_word
        while(True):
            wordIndex = np.random.choice(len(word_index_dict), 1, p=list(probs[word_index_dict[prevWord]]))
            word = index_word_dict[wordIndex[0]]
            returnSTR += word + " "
            num_words +=1
            prevWord = word
            if word == "</s>" or num_words == max_words:
                break

        return returnSTR


In [105]:
model_type = "unigram"

# model_type = "bigram"

max_words = 2

start_word = "all"

GENERATE(word_index_dict, probs, model_type, max_words, start_word)

'enabling the '

In [6]:
# r = {v : k for k,v in word_index_dict.items()}
# r

In [8]:
prevWord = "rob"

# list(probs[word_index_dict[prevWord]])

# probs[word_index_dict[prevWord]]

In [111]:
# list(probs[0])

In [9]:
# np.seed(3)
np.random.choice(10, 3)

array([4, 6, 4])

In [125]:
np.random.choice(5, 3, p = [0.2, 0.1, 0.3, 0.4, 0])

array([2, 3, 2])

In [150]:
np.array([5,2,8,9]).reshape(2,2)

array([[5, 2],
       [8, 9]])

In [14]:
m = np.zeros((813,2))
m

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [162]:
# from nltk import ngrams

# sentence = 'this is a foo bar sentences and i want to ngramize it'

# n = 2
# sixgrams = ngrams(sentence.split(), n)

# for grams in sixgrams:
#     print(grams)

('this', 'is')
('is', 'a')
('a', 'foo')
('foo', 'bar')
('bar', 'sentences')
('sentences', 'and')
('and', 'i')
('i', 'want')
('want', 'to')
('to', 'ngramize')
('ngramize', 'it')


In [212]:
with open("brown_vocab_100.txt") as f:
    vocab = [line.rstrip('\n') for line in f]


for ind, word in enumerate(vocab): 
    word_index_dict[word] = ind
    
    
with open("brown_100.txt") as f:
    brown = [line.rstrip('\n') for line in f]
#     brown = f.readline()
# brown = brown[0]
#brown

In [275]:
len(d5)

2368

In [273]:
d6 = {v : k for k,v in d5.items() }
d6

{('<s>', 'the'): 2202,
 ('the', 'fulton'): 792,
 ('fulton', 'county'): 705,
 ('county', 'grand'): 3,
 ('grand', 'jury'): 355,
 ('jury', 'said'): 609,
 ('said', 'friday'): 6,
 ('friday', 'an'): 7,
 ('an', 'investigation'): 8,
 ('investigation', 'of'): 9,
 ('of', "atlanta's"): 10,
 ("atlanta's", 'recent'): 11,
 ('recent', 'primary'): 12,
 ('primary', 'election'): 13,
 ('election', 'produced'): 14,
 ('produced', '``'): 15,
 ('``', 'no'): 16,
 ('no', 'evidence'): 17,
 ('evidence', "''"): 18,
 ("''", 'that'): 19,
 ('that', 'any'): 20,
 ('any', 'irregularities'): 21,
 ('irregularities', 'took'): 22,
 ('took', 'place'): 23,
 ('place', '.'): 24,
 ('.', '</s>'): 2367,
 ('the', 'jury'): 763,
 ('jury', 'further'): 28,
 ('further', 'said'): 29,
 ('said', 'in'): 30,
 ('in', 'term-end'): 31,
 ('term-end', 'presentments'): 32,
 ('presentments', 'that'): 33,
 ('that', 'the'): 1247,
 ('the', 'city'): 298,
 ('city', 'executive'): 36,
 ('executive', 'committee'): 2083,
 ('committee', ','): 38,
 (',', 'wh

In [274]:
len(d6)

1879

In [254]:
len(dic2)

1880

In [255]:
# dic2