In [1]:
import numpy as np

In [2]:
a1 = [1,2,3] # 00, 01 , 02
a2 = [4,5,6] # 10, 11 , 12
a3 = [7,8,9] # 20, 21 , 22

In [3]:
#output: 1 4 7 8 9 6 3 2 5 
#output = 00 ,10,  20 , 21, 22, 12, 02, 01, 11

In [4]:
n = np.array([a1, a2, a3])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
r = 3 
c = 3

In [6]:
# for i in range(r):
#     for j in range(c):
#         print(n[i][j])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#output: 1 4 7 8 9 6 3 2 5 
#output = 00 ,10,  20 , 21, 22, 12, 02, 01, 11
count = 0
steps = r * c
for i in range(r):
    for j in range(c):
        if count <  steps and i == j:
            print(n[i][j]) 
            count = count + 1

1
5
9


In [9]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#output: 1 4 7 8 9 6 3 2 5 
#output = 00 ,10,  20 , 21, 22, 12, 02, 01, 11
a1 = [1,2,3] # 00, 01 , 02
a2 = [4,5,6] # 10, 11 , 12
a3 = [7,8,9] # 20, 21 , 22
count = 0
steps = r * c
lr = 0
lc = 0
for i in range(r):
    for j in range(c):
        if count <  steps :
            if lc < c:
                
                print(n[i][lc]) 
                lr = lr + 1
                
                
        count = count + 1

1
1
1
4
4
4
7
7
7
