In [1]:
import pandas as pd
import numpy as np
import re 
from sklearn.preprocessing import normalize

In [17]:

# vocab = pd.read_csv('brown_vocab_100.txt' , header =None , sep='delimiter')
# print(vocab.shape)

(813, 1)


<ipython-input-17-bd49e55bd241>:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  vocab = pd.read_csv('brown_vocab_100.txt' , header =None , sep='delimiter')


In [2]:
# vocab.head(2)

In [40]:
word_index_dict = {}
# vocab = vocab[0]

# for ind, word in enumerate(vocab): 
#     word_index_dict[word] = ind

##############################################################

with open("brown_vocab_100.txt") as f:
    vocab = [line.rstrip('\n') for line in f]


for ind, word in enumerate(vocab): 
    word_index_dict[word] = ind
    
    
def save_dict_to_file(dic):
    f = open('word_to_index_100.txt','w')
    f.write(str(dic))
    f.close()

def load_dict_from_file():
    f = open('word_to_index_100.txt','r')
    data=f.read()
    f.close()
    return eval(data)

In [260]:
# word_index_dict

In [37]:
save_dict_to_file(word_index_dict1)

In [44]:
# load_dict_from_file()

In [9]:
print(word_index_dict['all'])
print(word_index_dict['resolution'])
print(len(word_index_dict))


0
812
813


In [14]:
# Question 2 : 
# brown = pd.read_csv('brown_100.txt' , header =None , sep='delimiter')
# brown.head(3)

In [1]:
# #dataframe
# a2 = np.zeros(813, dtype = "int")
# for sent in brown[0]:
#     text1 = re.sub('<s>|</s>', ' ', sent)
#     text2 = text1.lower().strip().split()
#     for word in text2:
#         if word in word_index_dict:
#             a2[word_index_dict[word]] = a2[word_index_dict[word]] +1
            
# a2

In [ ]:
#question 2) file

In [3]:
with open("brown_100.txt") as f:
    brown = [line.rstrip('\n') for line in f]
#     brown = f.readline()
# brown = brown[0]
# brown

In [33]:
len(brown)

100

In [13]:
brown[0]

"<s> The Fulton County Grand Jury said Friday an investigation of Atlanta's recent primary election produced `` no evidence '' that any irregularities took place . </s> "

In [49]:
#file 

def load_dict_from_file():
    f = open('word_to_index_100.txt','r')
    data=f.read()
    f.close()
    return eval(data)

word_index_dict = load_dict_from_file()
# word_index_dict

In [50]:

def count_word(word_input, word_index_dict_input):
    count_vector = np.zeros(813, dtype = "int")
    for sent in word_input:
        text1 = re.sub('<s>|</s>', ' ', sent)
        text2 = text1.lower().strip().split()
        for word in text2:
            if word in word_index_dict_input:
                count_vector[word_index_dict_input[word]] = count_vector[word_index_dict_input[word]] +1
                
    return count_vector


In [237]:
arr2 = count_word(brown, word_index_dict)
# arr2

In [94]:
arr2.shape

(813,)

In [95]:
# len(arr2)

In [127]:
probs = (arr2 / np.sum(arr2))
# probs

In [97]:
probs[0] , probs[-1]

(0.0004409171075837742, 0.003968253968253968)

In [98]:
"""
Write your new probs vector to a file called unigram_probs.txt and verify that the first probability in it
(the probability of ‘all’) is 0.00040519 and that the last probability (probability of ‘resolution’) is 0.00364668.
(Note that our model trained on this small corpus has estimated that ‘resolution’ is about 10 times as frequent as 
‘all’! Models trained on very small corpora are very noisy.)
"""

'\nWrite your new probs vector to a file called unigram_probs.txt and verify that the first probability in it\n(the probability of ‘all’) is 0.00040519 and that the last probability (probability of ‘resolution’) is 0.00364668.\n(Note that our model trained on this small corpus has estimated that ‘resolution’ is about 10 times as frequent as \n‘all’! Models trained on very small corpora are very noisy.)\n'

In [104]:
def GENERATE(word_index_dict, probs, model_type, max_words, start_word):
    returnSTR = ""
    index_word_dict = {v: k for k, v in word_index_dict.items()}
    num_words = 0

    #been passed a list of probabilities
    if model_type == "unigram":

        #using https://stackoverflow.com/questions/483666/python-reverse-invert-a-mapping
        while(True):
            wordIndex = np.random.choice(len(word_index_dict), 1, p=list(probs))
            word = index_word_dict[wordIndex[0]]
            returnSTR += word + " "
            num_words +=1
            if word == "</s>" or num_words == max_words:
                break

        return returnSTR

    #been passed a matrix of probabilities, where each row is the previous word. 
    if model_type == "bigram":
        returnSTR = start_word + " "
        prevWord = start_word
        while(True):
            wordIndex = np.random.choice(len(word_index_dict), 1, p=list(probs[word_index_dict[prevWord]]))
            word = index_word_dict[wordIndex[0]]
            returnSTR += word + " "
            num_words +=1
            prevWord = word
            if word == "</s>" or num_words == max_words:
                break

        return returnSTR


In [105]:
model_type = "unigram"

# model_type = "bigram"

max_words = 2

start_word = "all"

GENERATE(word_index_dict, probs, model_type, max_words, start_word)

'enabling the '

In [239]:
# r = {v : k for k,v in word_index_dict.items()}
# r

In [109]:
# t = word_index_dict
# t["rob"]

3

In [ ]:
count_vector = np.zeros(813, dtype = "int")
    for sent in word_input:
        text1 = re.sub('<s>|</s>', ' ', sent)
        text2 = text1.lower().strip().split()
        for word in text2:
            if word in word_index_dict_input:
                count_vector[word_index_dict_input[word]] = count_vector[word_index_dict_input[word]] +1
                

In [4]:

prev = '<s>'
dic3 = {}
total_count = 0
for sent in brown:
    text2 = sent.lower().strip().split()
    for word in text2:
        #print(prev,word)
        if not (prev,word) in dic3:
            dic3[(prev,word)]=1
            prev = word
        else:
            dic3[(prev,word)]+=1
            prev = word
            total_count += 1

In [30]:
def generate_combination_word(previous, brown_text):
    dic_word_count = {}
    total_count = 0
    
    for sent in brown_text:
        text = sent.lower().strip().split()
        for word in text:
            if not (previous,word) in dic_word_count:
                dic_word_count[(previous,word)]=1
                previous = word
            else:
                dic_word_count[(previous,word)]+=1
                previous = word
                total_count += 1
                
    dic_index_word = {}
    count = 0
    
    for i,v in dic_word_count.items():
        dic_index_word[count] = i
        count = count + 1
        
    return dic_word_count, dic_index_word, total_count


def count_matrix(dic_word_count_val, dic_index_word_val, total_count_val):
    array_count_matrix = np.zeros([len(dic_index_word_val),2])
        
    for i in range(0, len(dic_index_word_val)):
        array_count_matrix[i][0]= int(i)
        array_count_matrix[i][1]= dic_word_count_val[dic_index_word_val[i]] / total_count_val
        
    return array_count_matrix

In [31]:
prev = '<s>'
dic_word_count_value, dic_index_word_value, total_count_value = generate_combination_word(prev, brown)

In [32]:
total_count_value, total_count

(587, 587)

In [33]:
count = count_matrix(dic_word_count_value, dic_index_word_value, total_count_value)

In [35]:
from sklearn.preprocessing import normalize
probs_2 = normalize(count, norm='l1', axis=1)

In [36]:
count[0][0], count[6][1]

(0.0, 0.013628620102214651)

In [37]:
probs_2

array([[0.00000000e+00, 1.00000000e+00],
       [9.56026059e-01, 4.39739414e-02],
       [9.94915254e-01, 5.08474576e-03],
       ...,
       [9.99999093e-01, 9.07122453e-07],
       [9.99999093e-01, 9.06639685e-07],
       [9.99999094e-01, 9.06157430e-07]])

In [15]:
# dic4

In [5]:
dic3[('all', 'the')] / total_count

0.0017035775127768314

In [54]:
1 - 0.0017035775127768314

0.9982964224872232

In [6]:
dic4 ={}
a=0
for i,v in dic3.items():
    dic4[a]= i
    a=a+1

In [19]:
len(dic4)

1881

In [8]:
count_matrix = np.zeros([len(dic4),2])
count_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
for i in range(0,1881):
    count_matrix[i][0]= int(i)
    count_matrix[i][1]= dic3[dic4[i]] / total_count

In [10]:

count_matrix

array([[0.00000000e+00, 1.70357751e-03],
       [1.00000000e+00, 4.59965928e-02],
       [2.00000000e+00, 1.02214651e-02],
       ...,
       [1.87800000e+03, 1.70357751e-03],
       [1.87900000e+03, 1.70357751e-03],
       [1.88000000e+03, 1.70357751e-03]])

In [11]:
count_matrix[0][0], count_matrix[6][1]

(0.0, 0.013628620102214651)

In [12]:
from sklearn.preprocessing import normalize
probs = normalize(count_matrix, norm='l1', axis=1)

In [13]:
probs

array([[0.00000000e+00, 1.00000000e+00],
       [9.56026059e-01, 4.39739414e-02],
       [9.94915254e-01, 5.08474576e-03],
       ...,
       [9.99999093e-01, 9.07122453e-07],
       [9.99999093e-01, 9.06639685e-07],
       [9.99999094e-01, 9.06157430e-07]])

In [50]:
# dic_word_count_value
('the', 'fulton') in dic_word_count_value
dic_word_count_value[('all', 'the')]

1

In [53]:
dic_index_word_value[0], dic_index_word_value[2]

(('<s>', '<s>'), ('the', 'fulton'))

In [42]:
# dic_index_word_value[('the', 'all')]
dic_word_count_value[('the', 'all')]

KeyError: ('the', 'all')

In [55]:
# dic_word_count_value

In [56]:
# dic_index_word_value

In [90]:
dic_word_count_value[('all', 'the')] / total_count_value

0.0017035775127768314

In [91]:
dic_word_count_value[('all', 'the')] / total_count , dic_word_count_value[('the', "jury")] / total_count

(0.0017035775127768314, 0.022146507666098807)

In [92]:
dic_word_count_value[('the', "campaign")] / total_count , dic_word_count_value[('anonymous', "calls")] / total_count

(0.0017035775127768314, 0.0017035775127768314)

In [93]:
dic_word_count_value[('all', 'the')], dic_word_count_value[('the', "jury")],

(1, 13)

In [94]:
 dic_word_count_value[('the', "campaign")], dic_word_count_value[('anonymous', "calls")]

(1, 1)

In [95]:
val = ('all', 'the')
val1 = ('the', "jury")
val in dic_word_count_value

True

In [97]:
get_value(dic_word_count_value, val1) 

13

In [99]:
get_index(dic_index_word_value, val1) 

28

In [85]:
# dic3

In [89]:
probs[365][1]

4.667313867522963e-06

In [70]:
def get_value(dic, value):
    for k, v in dic.items():
        if k == value:
            return v

In [76]:
def get_index(dic, value):
    for i, v in dic.items():
        if v == value:
            return i

In [ ]:
p(the | all)
p(jury | the)
p(campaign | the)
p(calls | anonymous)

In [ ]:
probab = word_dict[word]/ total_count

In [57]:
    
def save_dict_to_file(prob_matrix):
    f = open('bigram_probs.txt','w')
    f.write(str(prob_matrix))
    f.close()

def load_dict_from_file():
    f = open('bigram_probs.txt','r')
    data=f.read()
    f.close()
    return eval(data)

In [58]:
save_dict_to_file(probs)

In [59]:
# prob3 = load_dict_from_file()

SyntaxError: invalid syntax (<string>, line 1)